,"Finally... We are getting to the bottom."
,"The powerful energy reaction... It seems that the culprit of the spatial distortion is down there."
,"...Hmm...?"
B,"Beepow?"
,"Am I misremembering?"
,"Wasn't there only one road here before...?"